import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import { cn } from "@/lib/utils";
import { NavigationMenuDemo } from '@/components/Header';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Francisco Fares Portfolio',
  description: 'Generated by Francisco Fares',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className,"min-h-screen bg-background")}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          {children}  
        </ThemeProvider>
      </body>
    </html>
  )
}
